server:
  port: 8080

spring:
  application:
    name: demo-spring-cloud-gateway
  cloud:
    # 配置nacos注册中心地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    # 配置网关信息
    gateway:
      enabled: true # 默认为True，是否开启网关
      discovery:
        locator:
          # 默认为False，设置为True开启通过微服务创建路由的功能，即可以通过微服务名称访问服务
          enabled: false
      #设置路由：路由id、路由到微服务的uri、断言
      routes:
      - id: user_route   # 路由ID，全局唯一，建议配合服务名
#        uri: http://localhost:8083    # 目标微服务的请求地址和端口
        uri: lb://demo-user
        predicates:
          - Path=/user/**
          - CheckAuth=luke
        filters:
          - CheckAuth=luke, 男